### ISSUE TITLE
Bindings are outdated

### ISSUE THREAD

**Issue by dmitry-egorov** [apptentive/apptentive-xamarin#2]
Hello! Are you planning to update the binding?

I'm trying to do it myself, but having trouble building apptentive-ios as .a library.

**Comment by msaffitz** [comment]
Hello.  Unfortunately we haven't seen a tremendous amount of demand for Xamarin support, and at the moment don't have any plans for further updates, nor are we able to offer official support for it.  We're actively investing in our native iOS and Android clients, and can make "best-effort" support if you wanted to update the Xamarin library and submit a pull request.

**Comment by dmitry-egorov** [comment]
Ok, I see.

I've created my own bindings here: https://github.com/dmitry-egorov/apptentive-xamarin-ios

It's building both apptentive-ios and binding dll with a makefile. You can use it, if you want, but note that I didn't test it thoroughly yet.
